services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  app:
    build:
      context: .
      target: development
    command: ["rails", "server", "-b", "0.0.0.0"]
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db

  test:
    build:
      context: .
      target: test
    command: bash -c "sleep 10 && bundle exec rake db:create db:schema:load db:test:prepare && bundle exec rspec"
    volumes:
      - .:/app
    environment:
      RAILS_ENV: test
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/quadro_vagas_rb_test
    depends_on:
      - db

volumes:
  postgres_data:
