name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: docker compose run test
        continue-on-error: false
      - name: Cleanup
        if: always()
        run: docker compose down --volumes --remove-orphans

  lint:
    runs-on: ubuntu-latest
    needs: test
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint Ruby files
        run: docker compose run -T app bundle exec rubocop
        continue-on-error: false
      - name: Cleanup
        if: always()
        run: docker compose down --volumes --remove-orphans
